//
//  RoundedImageView.swift
//  Top50FreeApps
//
//  Created by Aya Irshaid on 5/19/19.
//  Copyright © 2019 Aya Irshaid. All rights reserved.
//

import UIKit

@IBDesignable open class RoundedImageView: UIImageView {

    
    /// When positive, the background of the layer will be drawn with rounded corners. Also effects the mask generated by the `masksToBounds' property. Defaults to zero. Animatable.
    @IBInspectable var cornerRadius: Double {
        get {
            return Double(self.layer.cornerRadius)
        }
        set {
            self.layer.cornerRadius = CGFloat(newValue)
        }
    }
    
}
